### ISSUE TITLE
Ban system (Done)

### ISSUE THREAD

**Issue by Scuph** [Scuph/ScuphUtils#2]
Currently our custom ban command works but on a player join, if they are banned, they wont get the reason or sender. Just the default banned by an operator message. I plan on using the banUsername method, and making the url for appeal configurable by config, I would like @WickedGamingUK or @Paul19988's help with this, it would be greatly appreciated. :)

**Comment by LegendIsAwesomes** [comment]
Why not just put before they get banned (Or after) player.kickPlayer(ChatColor.RED "You where banned for " + reason "!"); or similar. Not seen the code yet.

**Comment by Scuph** [comment]
@LegendIsAwesomes I don't think you get how this works. Please review on what kickPlayer does.

**Comment by WickedGamingUK** [comment]
Don't use player.setBanned. That's the problem.

**Comment by LegendIsAwesomes** [comment]
@Scuph kick player kicks them from the game. After kicking them use player.setBanned(true); (Or before) to ban them. Or if they/or you have one use a custom ban.

**Comment by Scuph** [comment]
@WickedGamingUK should I make a Util.java and use the banUsername method?

**Comment by Paul19988** [comment]
Easily resolvable, compare their UUID on PrePlayerJoinEvent then check if on the ban list or such

**Comment by Scuph** [comment]
Thank you @Paul19988!

**Comment by Scuph** [comment]
Thank you @Wild1145 and @JeromSar for help, I have done this myself!

**Comment by WickedGamingUK** [comment]
I don't see any credit left from where you copied that from. @Wild1145

**Comment by Scuph** [comment]
@wickedgaminguk im working on that.

**Comment by Wild1145** [comment]
Thank you for brining this to my attention @WickedGamingUK, appropriate action is being taken.

**Comment by JeromSar** [comment]
@Scuph @Wild1145 Complete copy of DCMod's Ban.java: https://github.com/DarthCraft/DarthCraft/blob/master/src/net/darthcraft/dcmod/player/Ban.java

**Comment by Scuph** [comment]
As I completely copied DCMod, this is reopened and I want somebody to help me figure out how to use config strings in command so I can make things changeable for server owners.

If you can help, maybe a price can be brought up.
@Paul19988 @Wild1145 @WickedGamingUK @JeromSar
